### ISSUE TITLE
Formulário para palestrantes

### ISSUE THREAD

**Issue by InFog** [GCCSD/flisol-site#3]
Fazer um formulário para os interessados em palestrar ou fazer oficinas.

**Comment by diegosouza** [comment]
Pode ser bacana dar uma olhada no que já existe, como o call4papers.

**Comment by InFog** [comment]
Mas a ideia é instalar uma versão do C4P ou usar o C4P? Como funciona?

A minha ideia era um form simples, mandando e-mail para os organizadores.

**Comment by diegosouza** [comment]
Digo de repente só rodar o call4papers localmente pra ver como é o formulário.

**Comment by InFog** [comment]
Adicionei apenas uma informação para contatar o grupo na lista de discussão.

**Comment by InFog** [comment]
@diegosouza Criei o evento no call4paperz: http://call4paperz.com/events/flisol-santos-2015

Agora vou inserir o link no site :)

**Comment by diegosouza** [comment]
Legal, acho que ficou ótimo :+1:
