### ISSUE TITLE
Adicionar as fotos de 2014

### ISSUE THREAD

**Issue by InFog** [GCCSD/flisol-site#9]
Adicionar as fotos do Flisol de 2014.

Seria bacana ter algo como uma galeria que faz zoom nas fotos.

**Comment by diegosouza** [comment]
Será que vale a pena algo tipo [PhotoSwipe](https://github.com/dimsemenov/PhotoSwipe)?

**Comment by InFog** [comment]
Boa. Vale sim. Estou trabalhando nisso agora. Valeu, @diegosouza !

**Comment by InFog** [comment]
Feito. Acabei usando o galleria.io, mais simples :)
